version: "3"

services:
  backend:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - the_net
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - the_net

networks:
  the_net:
    driver: bridge
